batch_size : 64

rnn_units_size : 128 # LSTM 隐藏结点个数

rnn_layer_number : 2 # RNN 深度

vocabulary_vector_size : 4147 # 词向量长度，即总共有多少个词

share_embedding_with_output : False

learning_rate : 0.0005

max_epoch_num : 100